Check for connection of the gaming-mesa content interface and display an error

diff --git a/src/desktop-launch b/src/desktop-launch
--- a/src/desktop-launch
+++ b/src/desktop-launch
@@ -6,6 +6,13 @@
 # shellcheck disable=SC2034
 START=$(date +%s.%N)
 
+if ! snapctl is-connected "gaming-mesa"; then
+  echo "ERROR: not connected to the gaming-mesa content interface."
+  echo "To connect:"
+  echo "sudo snap connect steam:gaming-mesa gaming-graphics-core22"
+  exit 1
+fi
+
 # ensure_dir_exists calls `mkdir -p` if the given path is not a directory.
 # This speeds up execution time by avoiding unnecessary calls to mkdir.
 #
